### PR TITLE
Unable to read videoclip / voicemail

### PR DESCRIPTION
**Pull request by Minims**
Hello, 

First thanks for this tool, it very helpful to make the 300x working in HA.

This is not a real PR, but an issue.  It's not possible to open one on this repo.

Currently i can see i have one voicemail , but how can i play the video ? 

I'm also usion scrypted that see this voicemail, but i'm unable to play or download it.

Any idea can i do to make it work ?

Thanks !

/videoclips?raw=true
```
[{"file":"message_1","info":{"Date":"Sat,  2 Mar 2024 10:18:48 +0100","MediaType":"2","EuAddr":"20","cause":"0","Status":"0","UnixTime":"1709371128","Read":"1","Duration":"15"}}]
````

/voicemail
```
Found 1 messages.
 viewed - Sat,  2 Mar 2024 10:18:48 +0100
 ``

### CODE REVIEW

**Comment by slyoldfox** [comment]
This is handled here:
https://github.com/slyoldfox/c300x-controller/blob/main/lib/apis/voicemail-messages.js#L29

It looks for messages in the folder here defined here: 
https://github.com/slyoldfox/c300x-controller/blob/main/lib/apis/voicemail-messages.js#L3

The endpoint should normally be:
http://INTERCOM_IP:8080/voicemail?msg=message_1/aswm.avi&raw=true
http://INTERCOM_IP:8080/voicemail?msg=message_1/aswm.jpg&raw=true

Note that sometimes the jpg files are absent (if I remember correctly).

**Comment by Minims** [comment]
according to https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types
avi files need `video/x-msvideo`and not `video/mp4`

Now the link http://INTERCOM_IP:8080/voicemail?msg=message_1/aswm.avi&raw=true
 is working. Before my browser was unable to read/download the file. Only curl was able to do that.
 
 So the API works now with that header. Need to check why i still have issue inside scrypted now for voicemail.

**Comment by Minims** [comment]
So about Scrypted, i continue here for now as you are the main developper of the scrypted plugin too :-).

Download the voicemail is working on Scrypted only if your are connected to <IP>:10443.
I used the HA Scrypted Addons and the url is rewrite to <HA_adress>:<HA port>. Might be a scrypted issued. But it works.

But I cannot play the voicemail inside scrypted. All. HTTP call seems 200OK, But the data of `octet/stream` is not playing.
Tried on <IP>:10443 to avoid issue and on Arc, Chrome,Safari.

Do this is working on your side ?

**Comment by slyoldfox** [comment]
@Minims no, streaming hasn't worked ever.
Only the download "works" at the moment.
The reason is that the file is not a file that is able to support streaming.
I'll try and have a look at this coming days.

**Comment by slyoldfox** [comment]
@Minims try bticino plugin 0.0.15 with these changes in c300x-controller:

https://github.com/slyoldfox/c300x-controller/commit/8ea39ca22ce4d5c91a54b15064b2bd05a967cd40
https://github.com/slyoldfox/c300x-controller/commit/9a6a8977da56f32a10d28bfe97b29c1ef027f460

**Comment by slyoldfox** [comment]
Join channel #sip to on Discord https://discord.gg/DcFzmBHYGq if need more assistance

**Comment by Minims** [comment]
Thanks for the update, i will continue on discord.

FYI : 
 - Download from c300x-controller : OK
 - Stream from Scrypted : OK
 - Download from Scrypted :  FAIL

**Pull request closed without merging**
